version: '3.3'
services:
  # Database
  db:
    image: mysql:8.1
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment: 
      MYSQL_DATABASE: 
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - wp

  # WordPress
  wordpress:
    image: wordpress:6.3-fpm-alpine
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./www:/var/www/html
    networks:
      - wp
    depends_on:
      - db

  # Webserver
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - wp

  adminer:
    image: adminer
    restart:  unless-stopped
    ports:
      - 10000:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db

volumes:
  db:

networks:
  wp:
